### ISSUE TITLE
Say something about x265 (HEVC)

### ISSUE THREAD

**Issue by elboletaire** [mitio/useful-ffmpeg-commands#2]
I'm not an expert but, afaik, this codec usually has better compression and quality than x264.

https://unix.stackexchange.com/questions/230800/re-encoding-video-library-in-x265-hevc-with-no-quality-loss

**Comment by elboletaire** [comment]
Note that I said "usually". I tried it by myself and, in some cases the compression vs a 264 encoded video was better maintaining the quality, but in many cases I usually get files bigger thatn the ones encoded with x264. 

As said, I'm not an expert 😄

**Comment by mitio** [comment]
@elboletaire You're correct, x265 has a better compression than x264. However, it also requires more resources to decode and I've observed that some devices and players struggle with it.

My main experience has been with x264 and mpeg-4 and my main goal has been to produce outputs that should play flawlessly on a wide array of devices, including older and less powerful ones.

This repository is by no means a complete guide to ffmpeg or codecs and is just a collection of commands that I've compiled from various sources and that I've tested in practice. I use it myself as a reference when I forget how to do a certain operation :) Since I haven't yet played with x265, I've no commands to include there yet. However, I'm open to pull requests for examples with x265, if you have something in mind.

Since I've nothing more to add currently, I'll close this issue for now, but feel free to reopen it if you think we should discuss this further.

And thanks for taking the time to suggest this! I appreciate it!

**Comment by elboletaire** [comment]
Thanks for the response @mitio. I totally understand your point. The first times I downloaded files with x265 I had some issues playing it in Kodi (they fixed it), and in emby (also fixed it). After that I have not experienced any other issues, but I use emby a lot, and it automatically transcodes videos if the device requires it, so I'm not sure how many devices support it (BTW, I'm sure chromecast does not, as they only support x264).

Sincerely, as said, I'm not an expert. I started playing with x265 when I downloaded a TV series in 720p at a size of 350MB per episode. That's my goal xD. But as you may know, playing with ffmpeg is a bit painful... it's slow, and kills your CPU.

BTW, if I find any interesting command to convert videos to x265 I'll try to say it here before doing any PR, so you can try them by yourself first.

Oh, and thanks a lot for this guide! I really appreciate it. I'm always using google for each ffmpeg command I need xD
